# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Checks that are intended to run on PRs containing Java code.

name: Neo4j PR

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'v2/googlecloud-to-neo4j/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=error

permissions: read-all

jobs:
  neo4j_integration_test_templates:
    name: Neo4j Template Custom Integration Tests
    timeout-minutes: 60
    # Run on any runner that matches all the specified runs-on values.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup Environment
        id: setup-env
        uses: ./.github/actions/setup-env
      - name: Run Neo4j Custom Integration Tests
        env:
          DT_IT_ACCESS_TOKEN: "ya29.c.c0ASRK0GaJKWeyf0mIUeZqYGQqu9zulW4JUv1jkDAh9qTPytH644HnI62-x293DewMllEpzrWh7QU5wQmLvbbjjTpd5yz-fpxmwDFCPl1iMZLiT0VBUPVzMsa8pNJcaN5prJ2hzdJYuQM_FITvuduu4L1WSnendH-Sl7SDx4FbFXK4VvHBLgeqGGeobJIMgx_-m1eslj6BpQEjj19FbUfzjVXgqhPhrAU9fHk9RcMXCvQWs67UhJQU_U3OjanB6qhTJc6N4LOqk-Ox5Vbw_p1Ur3ZQ0GHZkbMqIexR5x2lnBOIDz9Noz6effmd_3M_iY59jC7jVC7BEBmG7hB6ezD7g8XwpRqugxEXI3NqfdaY9BdJvYDKdb9BB760Mcx8iNUoG8kz0Ygt1mLuA5F29o8-N-PqYYFn9rH2gy24Ya4griUPpsXhsuJqENi7Wbl6o--MzBwNMZEYSQrNSuX8xsWomKlC9hE16hmOGoTdLpY_ukZJXO3lyge51kNNFmEddYd57YpWVeBFVxUiCYxZfiLpZBa3uo9RLq3XGykXYityH6fnMwYZm19HQ7mKRqFjbzFreI7KXVwjWymqfLta9fiuIgpYAIfs3zwYGKIyxv5aI598FjJk1vDJXN7E_tyvL645P5n6vh3mi8zU8IW3cazQamrMVaivzJw2FOaBockiYXr8QXhYjc0h61l-jFe_RvSRmlJBdfic6uWe9lac35Jt9MoQ_J0fqWfb8sSbrSRXVVcO20-gBbtyb8_9msQzzzruQuZobv8mc_nQWnckQ8S3g2vqUXfuyy1kzRhY1hY98Y-9__ec0-1yaaOym90tV8I7vF4fk4iXp5rl39OVxVfsw4W_ZBnu6VgFXB--pl5rphemcUZzf5qymfJ93XVMybOrIdSboxnnWibR2tFvYYkosQxaXQwzfofg3vwgJSBVy7Q_cR-043MBR4vfuO322mr-_yjsSqZXZqlZW0y06QrIm-70u8z0rs6t0W2VduU3jh-_ScMWlSivxU3"
        run: |
          mvn --also-make --projects v2/googlecloud-to-neo4j verify \
          -Djib.skip \
          -Djacoco.skip \
          -DskipShade \
          -Dspotless.check.skip \
          -Dcheckstyle.skip \
          -Dmdep.analyze.skip \
          -Dexcluded.neo4j.tests="" \ 
          -Dgroups=com.google.cloud.teleport.v2.neo4j.templates.Neo4jCustomTestCategory \ 
          -Dproject=team-connectors-dev \
          -PtemplatesIntegrationTests
      - name: Upload Tests Report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always() # always run even if the previous step fails
        with:
          name: surefire-test-results
          path: '**/surefire-reports/TEST-*.xml'
          retention-days: 1
      - name: Cleanup Java Environment
        uses: ./.github/actions/cleanup-java-env
        if: always()